# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- feature/*

pool:
  vmImage: windows-latest #code coverage is supported on windows image only

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Building - $(buildConfiguration)'
  inputs:
    command: build
    projects: '**/*.sln'
    arguments: '--configuration $(buildConfiguration)'
    requestedMajorVersion: 6
    requestedMinorVersion: 0

- task: DotNetCoreCLI@2
  displayName: 'Run unit tests - $(buildConfiguration)'
  inputs:
    command: test
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    projects: '**/*Test/*.csproj'
    publishTestResults: true
    requestedMajorVersion: 6
    requestedMinorVersion: 0