# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - feature/*

pool:
  vmImage: ubuntu-latest #code coverage is supported on windows image only

variables:
  buildConfiguration: 'Release'
  imageName: 'covid-covidservice-docker'
stages:
  - stage: Test
    displayName: 'Test environment'
    jobs:
      - job: BuildCovidService
        displayName: 'Build CovidService'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Building - $(buildConfiguration)'
            inputs:
              command: build
              projects: '**/*.sln'
              arguments: '--configuration $(buildConfiguration)'
              requestedMajorVersion: 6
              requestedMinorVersion: 0

          - task: DotNetCoreCLI@2
            displayName: 'Running unit tests - $(buildConfiguration)'
            inputs:
              command: test
              arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
              projects: '**/*Test/*.csproj'
              publishTestResults: true
              requestedMajorVersion: 6
              requestedMinorVersion: 0
          
      - job: PublishCovidService
        displayName: 'Publishing CovidService'
        condition: eq(variables['Build.SourceBranchName'], 'main')
        steps:
          - task: Docker@2
            displayName: 'Building and pushing Docker image'
            inputs:
              containerRegistry: 'antonvetrov-acr-connection'
              repository: 'covid-repository'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '**/../'
              tags: |
                latest
                $(Build.BuildId)